/* gcc hyp.c -nostdlib -fPIC -shared -o vmi.so */
void entry ()
{
    asm (
            "movl $0x0, %edx; \n\t"
            "movl 8(%edx), %eax; \n\t" // size in byte

            "3: \n\t"
            "movl $0x0, %edx; \n\t"
            "movl 4(%edx), %edx; \n\t" // source address
            "movl %cr3, %ecx; \n\t"
            "movl %ebx, %cr3; \n\t"

            "movl $0, %ebp; \n\t" // counter to record how many time we copied

            "movups (%edx), %xmm0; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 16(%edx), %xmm1; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 32(%edx), %xmm2; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 48(%edx), %xmm3; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 64(%edx), %xmm4; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 80(%edx), %xmm5; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 96(%edx), %xmm6; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"
            "cmpl $0, %eax; \n\t"
            "jle 1f; \n\t"
            "movups 112(%edx), %xmm7; \n\t"
            "inc %ebp; \n\t"
            "subl $16, %eax; \n\t"

            "1: \n\t"
            "movl %ecx, %cr3; \n\t"

            "movl $8, %edi; \n\t"
            "movl (%edi), %edi; \n\t"
            "subl %eax, %edi; \n\t" 
            "movl $12, %edx; \n\t"
            "addl %edx, %edi;\n\t"

            "movl %ebp, %esi; \n\t"
            "shll $4, %esi; \n\t"
            "movups %xmm0, (%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm1, 16(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm2, 32(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm3, 48(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm4, 64(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm5, 80(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm6, 96(%edi, %esi); \n\t"
            "dec %ebp; \n\t"
            "cmpl $0, %ebp; \n\t"
            "jle 2f; \n\t"
            "movups %xmm7, 112(%edi, %esi); \n\t"
            "dec %ebp; \n\t" // %ebp should be zero now

            "2: \n\t"

            "cmpl $0, %eax; \n\t"
            "jg 3b; \n\t"

            "vmcall; \n\t"
            );
}
